# Generated by Django 4.0.2 on 2022-02-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rate', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('is_published', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Old')])),
            ],
        ),
    ]
