# Generated by Django 4.0.2 on 2022-02-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Old')], default=0),
        ),
    ]
